### ISSUE TITLE
Youtube, Mastadon, Twitch urls are not case sensitive

### ISSUE THREAD

**Issue by webVerts** [authifyWeb/authifyNow#14]
Similar to https://github.com/authifyWeb/authifyURL/issues/5

**Comment by authifyAlly** [comment]
- [x] Youtube
- [ ] Mastadon
- [ ] Twitch

**Comment by webVerts** [comment]
Youtube Channels has 3 URL variation, [Handle URLs, custom URLs, and legacy username URLs].(https://support.google.com/youtube/answer/6180214?hl=en)

Channel ID : youtube.com/channel/UCkRfArvrzheW2E7b6SVT7vQ
Creator ID : youtube.com/@youtubecreators
Legacy URL : youtube.com/c/YouTubeCreators

**Comment by webVerts** [comment]
Due to being decentralized structre, Mastadon won't work.
Added Support for YT and Twitch in [v0.1.2](https://github.com/authifyWeb/authifyNow/releases/tag/v0.1.2)
