### ISSUE TITLE
Add extra information on not verified URL's to check with url.authifyweb.com

### ISSUE THREAD

**Issue by webVerts** [authifyWeb/authifyNow#30]
authifyNow is positioned as a solution for very high important brands and companies like banking and major ecommerce. This is done so that result will load faster. When tested for 10000+ company name, there will be a minimum of 7-10 seconds delay when showing the result. 

So a search for a URL from a smaller company will not be verified as it won't be available in the database. Therefore add a link to https://url.authifyweb.com as it will have a much bigger database. And the search will be faster.

**Comment by authifyAlly** [comment]
With the introduction of using API, to serve the data, authifyNow is faster than authifyURL. 
Also, for both the projects data is served from a common database. Therefore there is no differentiation for the company or brands, all are served equally.
