### ISSUE TITLE
Remove @ in yt profiles

### ISSUE THREAD

**Issue by webVerts** [authifyWeb/authifyNow#32]
Inside YT filter section
`
else if(pathname[1]=="@"){link= hostname+'/'+pathname.split('/')[1].replace('@','').toLowerCase();}
`
Related #https://github.com/authifyWeb/authifyFame/pull/3/

**Comment by webVerts** [comment]
Not always a suitable solution. Example channel: `https://www.youtube.com/@himalayawellnessindia`.

when removing the `@` the channel redirects to 404.

**Comment by authifyAlly** [comment]
Due to the issue mentioned above this will not be fixed. There are instances when removing '@' results in redirecting to 404 page or some other channel/user.
